# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            ''
tagline:          'Isabela Astiz Le Bras'
description:      'Isabela Astiz Le Bras Physical Oceanographer  <a href="https://twitter.com/oceanslebrasi" target="_blank">@oceanslebrasi</a>'
url:              http://ilebras.github.io
baseurl:          /


paginate:         5
