# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            ''
tagline:          'Isabela Astiz Le Bras'
description:      'Isabela Astiz Le Bras · Physical Oceanographer'
url:              http://ilebras.github.io
baseurl:          /


paginate:         5
