# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            
tagline:          ''
description:      'Isabela Astiz Le Bras, Ph.D. \n Postdoctoral Scholar \n Scripps Institution of Oceanography'
url:              http://ilebras.github.io
baseurl:          /

author:
  name:           'Isabela Le Bras'
  url:            https://twitter.com/oceanslebrasi

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/ilebras/ilebras.github.io
