# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            'Isabela Astiz Le Bras
tagline:          ''
description:      'Postdoctoral Scholar
		    Scripps Institution of Oceanography'
url:              http://ilebras.github.io
baseurl:          /

author:
  name:           'Isabela Le Bras'
  url:            https://twitter.com/oceanslebrasi

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/ilebras/ilebras.github.io
